### ISSUE TITLE
[feature] Option to disable Headless Asset Cache

### ISSUE THREAD

**Issue by Merith-TK** [Remora/Remora.Neos.Headless#1]
This feature is in place so that the Headless can, should the Client be unable to load from official sources, stream the assets to the client.

*however* this comes at an heavy storage cost as after a single week of operation, with only an *handful* of players (five tops, only two actually doing work on the world), rapidly build up to 20gb of storage used as both the Headless and the Client do not have the ability by default to clean up unused caches

Plus there may be instances where server hosts may need to monitor their network usage as they may be only allowed an certain amount a month (my VPS has an 2tb up/down total limit per month, others may not be so generous)

This would be three options to configure here
1. Disable Asset Cache, (default: false)
  - Disables caching assets locally, 
  - overrides 2 and 3 to both be false when true
2. Disable YoutubeDL (default: true)
  - Disables YoutubeDL integration
3. CacheClear, <string> (could be hours as int)
  - Deletes files that have not been accessed for X duration
    - 2d: two days
    - 2m: two months
    - 2h: two hours

**Comment by Nihlus** [comment]
Disabling the local asset caching outright is probably not possible, but having a periodic cleanup procedure should be easy enough. Preview 5 has some new options for this.
