### ISSUE TITLE
Option to Define Different LiteDB Cleanup Procedures

### ISSUE THREAD

**Issue by stiefeljackal** [Remora/Remora.Neos.Headless#3]
~~From my understanding, it appears that an automatic cleanup feature for LiteDB has been implemented. This is a great feature for most headless servers, but there are a few that would like to retain their LiteDB without it being tampered with. Therefore, there should be an option to disable this cleanup process.~~

Additionally, the cleanup procedure should be customized to cleanout certain types of assets imported. For example, `local://` entries and search queries made via the RedX facet are also populated into LiteDB. The headless will never save RedX query entries, but it will save `local://` entries. With that said, it might be good to implement for different types since some may want `local://` entries cleaned but keep `neosdb://` entries intact or clean those out at different iterations.

**Comment by Nihlus** [comment]
You can disable it by setting the cleanup interval to null or omitting the configuration key. I'll look into the other suggestions!

EDIT: null, not 0. Sorry!

**Comment by stiefeljackal** [comment]
Shoot. I missed the null check there. That is good to know it is there. I can change the title to reflect the suggestion if you want.

**Comment by Nihlus** [comment]
Please do :)
