### ISSUE TITLE
[feature] Userdefined GC events

### ISSUE THREAD

**Issue by Merith-TK** [Remora/Remora.Neos.Headless#5]
Allow the user to choose to enable force ran `gc` commands, can be `onSave`, or `onCleanup` (for asset cleanup), or even just every period of time the user chooses

**Comment by Nihlus** [comment]
This is not planned at the moment.

 I would rather focus on fixing memory issues at the source instead of giving end users rope to hang themselves with - there is practically never a good reason or time to run the GC manually that the GC doesn't already know about.
