### ISSUE TITLE
[feature] setup "log rotator" instead of serilog in config

### ISSUE THREAD

**Issue by Merith-TK** [Remora/Remora.Neos.Headless#7]
Modify it so the user can define an default LogsFolder, which will automatically write logs to that folder as if the user defined Serlilog to do so, but on start it will automatically rotate out the last log before creating an new one (`/var/lib/neosvr/logs/latest.log` gets moved to `log-<last edit time/date>.log`

This will make it easier for users to provide logs for debugging as not many (myself included) know how to use `journalctl` to its fullest extent, and some (myself included) find its use tedious as the command almost everyone is familiar with `journalctl -xe` shows *all* logs from *everything*, which congests it, and due to how it formats itself inside its little renderer, providing an full copy/paste of an error can be tedious as it by default does not "wrap text" 

And as with most programs, it is difficult to monitor. An dedicated default logfile system would be helpful because an user can look at the logs after the fact and find out, 

I personally have difficulty getting logs to you when remora crashes because it by default, automatically restarts, and Neos *logs a metric shit ton* to the console making it long and tedious to even scroll up to the previous runtime logs after it restarts in journalctl

**Comment by Nihlus** [comment]
You can do this with Serilog's configuration already: https://github.com/serilog/serilog-settings-configuration
