### ISSUE TITLE
[feature] [non-priority] Pre/Post Launch commands

### ISSUE THREAD

**Issue by Merith-TK** [Remora/Remora.Neos.Headless#8]
Have an section in Remora config, for pre/post launch commands, this would allow users to specify certain commands to run before Remora starts, such as an script to automatically rotate the log files, or update the Headless software, and allow for them to run their own asset cleanup script after its done running

**Comment by Nihlus** [comment]
You can do this by adjusting the systemd service (`ExecStartPre`, `ExecStopPost`, etc). It's also possible to define your own oneshot services that start or stop along with the headless.

At the moment, I don't think it's appropriate to add this to the headless itself. Better to let the surrounding execution environment deal with it.
